/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-30 06:45:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxkj.common.util.SystemGlobals;
import java.util.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>");
      out.write("\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<!-- The styles -->\r\n");
      out.write("\t<link id=\"bs-css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/bootstrap-cerulean.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link id=\"bs-css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link id=\"bs-css\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/easyui/jquery-1.10.2.min.js\"> </script>\r\n");
      out.write("\t<script type=\"text/javascript\">if(window.top != window){\r\n");
      out.write("\t\t\twindow.top.location = window.location;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t}</script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t  body {\r\n");
      out.write("\t\tpadding-bottom: 40px;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  .llwidth{\r\n");
      out.write("\t  \twidth:200px;\r\n");
      out.write("\t  }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("  function loginfn(btn){\r\n");
      out.write("  \r\n");
      out.write("  \tvar name = $(\"#username\").val();\r\n");
      out.write("  \tvar pass = $(\"#password\").val();\r\n");
      out.write("  \tvar url = \"");
      out.print(request.getContextPath());
      out.write("/admin/dologin\";\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t\t  type:'post',\r\n");
      out.write("\t\t\t  url: url,\r\n");
      out.write("\t\t\t  context: document.body,\r\n");
      out.write("\t\t\t  beforeSend:function(){\r\n");
      out.write("\t\t\t  \t\t// $(btn).attr('disabled','disabled');\r\n");
      out.write("\t\t\t\t },\r\n");
      out.write("\t\t\t  data:{\r\n");
      out.write("\t\t\t\t  name: name,pass:pass\r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t\t  success:function(json){\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t  \t\t//json = jQuery.parseJSON(json);\r\n");
      out.write("\t\t\t\t \t var result = json[\"result\"];\r\n");
      out.write("\t\t\t\t \t if(result){\r\n");
      out.write("\t\t\t\t \t \twindow.location = \"");
      out.print(request.getContextPath());
      out.write("/admin/index\";\r\n");
      out.write("\t\t\t\t \t }else{\r\n");
      out.write("\t\t\t\t \t \t var user = json.entity;\r\n");
      out.write("\t\t\t\t \t \t if(!user){\r\n");
      out.write("\t\t\t\t \t \t \talert(\"用户名或者密码错误\");\r\n");
      out.write("\t\t\t\t \t \t }else {\r\n");
      out.write("\t\t\t\t \t \t \tvar status = user.status;\r\n");
      out.write("\t\t\t\t \t \t \tif(status != 1){\r\n");
      out.write("\t\t\t\t \t \t \t\talert(\"您已经被锁定,请与管理员联系\");\r\n");
      out.write("\t\t\t\t \t \t \t}\r\n");
      out.write("\t\t\t\t \t \t }\r\n");
      out.write("\t\t\t\t \t }\r\n");
      out.write("\t\t\t\t \t  \r\n");
      out.write("\t\t\t  },\r\n");
      out.write("\t\t      error:function(xhr,textStatus,errorThrown){\r\n");
      out.write("\t\t  \t\tvar responseText = xhr.responseText;\r\n");
      out.write("\t\t  \t\t// $(btn)).removeAttr(\"disabled\");\r\n");
      out.write("\t\t  } \r\n");
      out.write("  })\r\n");
      out.write(" }\r\n");
      out.write("  </script>\r\n");
      out.write("  </head>\r\n");
      out.write("\r\n");
      out.write("  <body>\r\n");
      out.write("\r\n");
      out.write("     <div class=\"container-fluid\" >\r\n");
      out.write("\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"span12 center login-header\" style=\"height:100px;\">\r\n");
      out.write("\t\t\t\t\t<h2>高新科技管理员系统</h2>\r\n");
      out.write("\t\t\t\t</div><!--/span-->\r\n");
      out.write("\t\t\t</div><!--/row-->\r\n");
      out.write("\t\t\t<div class=\"row-fluid\">\r\n");
      out.write("\t\t\t\t<div class=\"well span5 center login-box\"   >\r\n");
      out.write("\t\t\t\t\t");
 
						Boolean userNameError = (Boolean)request.getAttribute("userNameError");
						 Boolean userPasswordError = (Boolean)request.getAttribute("userPasswordError");
						if(userNameError  !=null && userNameError.booleanValue()){
						 
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-info\">\r\n");
      out.write("\t\t\t\t\t\t用户名不正确\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

						}
						if(userPasswordError!=null && userPasswordError.booleanValue()){
					 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"alert alert-info\">\r\n");
      out.write("\t\t\t\t\t\t\t用户名或者密码不正确\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t");

							}
							
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t<!-- \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-prepend\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-road\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"flag\"  class=\"input-large llwidth\"   title=\"用户角色\" data-rel=\"tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"1\">教师</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"2\">学生</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </select>\r\n");
      out.write("\t\t\t\t\t\t\t </div>\r\n");
      out.write("\t\t\t\t\t\t -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-prepend\" title=\"用户名\" data-rel=\"tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-user\"></i></span><input autofocus class=\"input-large llwidth\" name=\"username\" id=\"username\" type=\"text\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-prepend\" title=\"密码\" data-rel=\"tooltip\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-lock\"></i></span>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input-large llwidth\" name=\"password\" id=\"password\" type=\"password\" value=\"\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"center span5\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\"   onclick=\"loginfn(this);\">登陆</button>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div><!--/span-->\r\n");
      out.write("\t\t\t</div><!--/row-->\r\n");
      out.write("\t\t\t\t</div><!--/fluid-row-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div><!--/.fluid-container-->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
