/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2014-11-30 07:44:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.gxkj.common.util.SystemGlobals;
import java.util.*;
import com.gxkj.taobaoservice.entitys.*;

public final class userhome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh\">\r\n");
      out.write("<head>");
      out.write("\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE8\" content=\"ie=edge\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>用户中心</title>\r\n");
      out.write("\t<link  href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/bootstrap-cerulean.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link  href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/bootstrap-responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link   href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/charisma-app.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/colorbox.css\" rel='stylesheet'>\r\n");
      out.write("\t<link href='");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/noty_theme_default.css' rel='stylesheet'>\r\n");
      out.write("\t<link   href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/css/jquery.noty.css\" rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body  >\r\n");
      out.write("\t<div class=\"row-fluid sortable\" >\r\n");
      out.write("\t\t\t\t<div class=\"box span12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"box-header well\" data-original-title>\r\n");
      out.write("\t\t\t\t\t\t<h2>修改密码</h2>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"box-content\"  >\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-horizontal\">\r\n");
      out.write("\t\t\t\t\t\t  <fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t  <label class=\"control-label\" for=\"newpassword\">新密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input class=\"input-xlarge focused\" id=\"newpassword\" type=\"password\" name=\"newpassword\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${newpassword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"control-group\">\r\n");
      out.write("\t\t\t\t\t\t\t  <label class=\"control-label\" for=\"confirmpassword\">确认密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"controls\">\r\n");
      out.write("\t\t\t\t\t\t\t\t  <input class=\"input-xlarge focused\" id=\"confirmpassword\" type=\"password\" name=\"confirmpassword\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${confirmpassword }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-actions\">\r\n");
      out.write("\t\t\t\t\t\t\t  <button type=\"button\" class=\"btn btn-primary\" onclick=\"submitFn()\">保存</button>\r\n");
      out.write("\t\t\t\t\t\t\t  <button type=\"reset\" class=\"btn\">重新输入</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t  </fieldset>\r\n");
      out.write("\t\t\t\t\t\t</form>   \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div><!--/span-->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write(" \r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/charisma/js/jquery.noty.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function submitFn(){\r\n");
      out.write("\tvar newpassword = $.trim($(\"#newpassword\").val());\r\n");
      out.write("\tvar confirmpassword = $.trim($(\"#confirmpassword\").val());\r\n");
      out.write("\t\r\n");
      out.write("\tif(newpassword.length == 0){\r\n");
      out.write("\t\tvar options = {\"text\":\"新密码不能为空\",\"layout\":\"topRight\",\"type\":\"error\"};\r\n");
      out.write("\t\tnoty(options);\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(confirmpassword.length == 0){\r\n");
      out.write("\t\tvar options = {\"text\":\"确认密码不能为空\",\"layout\":\"topRight\",\"type\":\"error\"};\r\n");
      out.write("\t\tnoty(options);\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(confirmpassword != newpassword){\r\n");
      out.write("\t\tvar options = {\"text\":\"确认密码与新密码不一致\",\"layout\":\"topRight\",\"type\":\"error\"};\r\n");
      out.write("\t\tnoty(options);\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\t\t\t  \t  \t  type:'post',\r\n");
      out.write("\t\t\t\t\t\t  url: \"");
      out.print(request.getContextPath() );
      out.write("/admin/user/setmypassword\",\r\n");
      out.write("\t\t\t\t\t\t  context: document.body,\r\n");
      out.write("\t\t\t\t\t\t  data:{\r\n");
      out.write("\t\t\t\t\t\t  \t  \r\n");
      out.write("\t\t\t\t\t\t  \t password:newpassword,\r\n");
      out.write("\t\t\t\t\t\t  \t confirmpassword:confirmpassword\r\n");
      out.write("\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t  success:function(json){\r\n");
      out.write("\t\t\t\t\t\t //\tjson = jQuery.parseJSON(json);\r\n");
      out.write("\t\t\t\t\t\t \tif(!json['result']){\r\n");
      out.write("\t\t\t\t\t\t \t \tvar msg = json[\"msg\"];\r\n");
      out.write("\t\t\t\t\t\t\t\tvar options = {\"text\":msg,\"layout\":\"topRight\",\"type\":\"error\"};\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnoty(options);\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t \t}else{\r\n");
      out.write("\t\t\t\t\t\t \t\tvar options = {\"text\":\"保存成功\",\"layout\":\"topRight\",\"type\":\"success\",timeout:1000};\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnoty(options);\r\n");
      out.write("\t\t\t\t\t\t \t}\r\n");
      out.write("\t\t\t\t\t\t \t \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  },\r\n");
      out.write("\t\t\t\t\t\t  error:function(xhr,textStatus,errorThrown){\r\n");
      out.write("\t\t\t\t\t\t  \t\t \r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t  } \r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
